---
- hosts: "{{ an_hosts }}"
  gather_facts: true
  remote_user: "{{ an_user_deploy }}"
  # vars_files:                                     # include by default
  #   - group_vars/all/general.yml                  # include by default
  #   - group_vars/all/secrets.yml                  # include by default
  tasks:
    - name: Provisioning - config
      include: pb/provisioning-config.yml

    - name: Provisioning - packages
      include: pb/provisioning-packages.yml

    - name: Provisioning - users
      include: pb/provisioning-users.yml

    - name: Provisioning - repos
      include: pb/provisioning-repos.yml


# ansible-playbook -e "an_hosts=${AN_HOSTS}" -e "an_user_deploy=${AN_USER_DEPLOY}" run-pb.yml