---
- name: Create folder ansible deploy
  include_role:
    name: 'folders'
  with_items:
    - '{{ an_path }}'
    - '{{ an_repos }}'
    - '{{ an_tmp }}'
    - '{{ an_local }}'
    - '{{ an_log }}'
    - '{{ an_log }}/history'