---
- name: Config files - aliases
  blockinfile:
    path: /etc/bash.bashrc
    block: |
        # Ansible deploy
        export AN_PATH="{{ an_path }}"
        export AN_LOG="{{ an_log }}"
        export AN_LOCAL="{{ an_local }}"
        export AN_REPOS="{{ an_repos }}"
        export AN_TMP="{{ an_tmp }}"
        alias cd_an_path="cd {{ an_path }}"
        alias cd_an_log="cd {{ an_log }}"
        alias cd_an_local="cd {{ an_local }}"
        alias cd_an_repos="cd {{ an_repos }}"
        alias cd_an_tmp="cd {{ an_tmp }}"

        # Set History
        export HISTTIMEFORMAT="%F %T: "
        export HISTFILE={{ an_log }}/history/history-$(whoami | awk '{print $1}' ; exit).log
        export PROMPT_COMMAND='history -a'

        # Load custom alias
        if [ -f ~/.bash_aliases_custom ]; then
            . ~/.bash_aliases_custom
        fi

        if [ -f ~/.bash_aliases_secrets ]; then
            . ~/.bash_aliases_secrets
            export REPO_CONFIG="~/repos/config"
            export CLOUD_PATH="~/cloud"
        fi