---
# Set Admin password before execute this role
- name: Enable Active directory
  win_feature:
    name: AD-Domain-Services
    state: present
    include_sub_features: yes
    include_management_tools: yes
  when: ansible_facts.memtotal_mb == 4096
  register: win_feature

- name: Reboot if installing feature requires it
  win_reboot:
  when: win_feature.changed == true

- name: Enable Active directory tools
  win_feature:
    name: RSAT-ADDS
    state: present
    include_sub_features: yes
    include_management_tools: yes

- name: Create new Windows domain in a new forest with specific parameters
  win_domain:
    create_dns_delegation: no
    database_path: C:\Windows\NTDS
    dns_domain_name: "{{domain_name}}.{{domain_ext}}"
    domain_mode: Win2012R2
    domain_netbios_name: "{{ domain_name | upper }}"
    forest_mode: Win2012R2
    safe_mode_password: "{{domain_password}}"
    sysvol_path: C:\Windows\SYSVOL
  register: domain_install

- name: Reboot 
  win_reboot: 