---
- name: Folder ansible workspace
  include_role:
    name: filesystem
    tasks_from: folder
  with_items:
    - '{{ an_path }}'
    - '{{ an_repos }}'
    - '{{ an_tmp }}'
    - '{{ an_local }}'
    - '{{ an_log }}'
    - '{{ an_log }}/history'