---
- name: Folder workspace
  include_role:
    name: filesystem
    tasks_from: folder
  with_items:
    - { folder: '{{ an_path }}', user: '{{ an_user_deploy }}' }
    - { folder: '{{ an_repos }}', user: '{{ an_user_deploy }}' }
    - { folder: '{{ an_tmp }}', user: '{{ an_user_deploy }}' }
    - { folder: '{{ an_local }}', user: '{{ an_user_deploy }}' }
    - { folder: '{{ an_log }}', user: '{{ an_user_deploy }}' }
    - { folder: '{{ an_log }}/history', user: '{{ an_user_deploy }}' }

- name: Config - aliases
  include_role:
    name: filesystem
    tasks_from: conf-aliases

- name: Config - sysctl
  include_role:
    name: filesystem
    tasks_from: conf-sysctl

- name: Config - locale
  vars: 
    - an_location: es_ES.UTF-8
  include_role:
    name: locale
