---
- name: Folder workspace
  include_role:
    name: filesystem
    tasks_from: folder
  with_items:
    - '{{ an_path }}'
    - '{{ an_repos }}'
    - '{{ an_tmp }}'
    - '{{ an_local }}'
    - '{{ an_log }}'
    - '{{ an_log }}/history'

- name: Config - aliases
  include_role:
    name: filesystem
    tasks_from: conf-aliases

- name: Config - sysctl
  include_role:
    name: filesystem
    tasks_from: conf-sysctl

- name: Config - locale
  vars: 
    - an_location: es_ES.UTF-8
  include_role:
    name: locale
